sudo: required
language: ruby
rvm:
- 2.1
before_install:
- openssl aes-256-cbc -K $encrypted_2d450156d8ea_key -iv $encrypted_2d450156d8ea_iv
  -in deploy_key.enc -out deploy_key -d
- gem install jekyll bundler
install:
- bundle install
script:
- bash ./.deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 2d450156d8ea
  - COMMIT_AUTHOR_EMAIL: mars@fusemachines.com
